<a href="https://colab.research.google.com/github/Lyanan85/In-GameSeries/blob/venv/centro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [50]:
df=pd.read_csv("/content/Orçamentos Totalis Odonto Centro 10-02-2025 a 21-06-2025 (1).csv")

In [51]:
print(df.columns)

Index(['Unnamed: 0', 'Cód', 'Orçamento', 'Cliente', 'Total', 'Pago', 'Devedor',
       'Pagamento fora do período', 'Dentista'],
      dtype='object')

In [52]:
mapeamento_dentistas = {
    "LUCIANE ALVES NUNES":"LUCIANE ALVES NUNES"}
# Aplicar o mapeamento
df['Dentista'] = df['Dentista'].str.strip().str.lower().replace(mapeamento_dentistas).str.title()

df.to_csv("df_inicial.csv",index=False)

In [53]:
df["Orçamento"] = pd.to_datetime(df["Orçamento"], format="%d/%m/%Y %H:%M", errors="coerce")
def dia_da_semana(data):
    dias = {
        0: "Segunda-feira",
        1: "Terça-feira",
        2: "Quarta-feira",
        3: "Quinta-feira",
        4: "Sexta-feira",
        5: "Sábado",
        6: "Domingo"
    }
    if pd.notnull(data):
        return dias[data.weekday()]
    return None
df["Dia_semana"]=df["Orçamento"].apply(dia_da_semana)
df

,Unnamed: 0,Cód,Orçamento,Cliente,Total,Pago,Devedor,Pagamento fora do período,Dentista,Dia_semana
0,0,27434,2025-02-10 09:53:00,5020538 - FABIA MOTA VASCONCELOS,150.0,150.0,0.0,-,Ana Karine Duarte Maia,Segunda-feira
1,1,27467,2025-02-11 10:00:00,5055076 - RENARA MIRANDA,300.0,300.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira
2,2,27469,2025-02-11 10:36:00,5054903 - ANA LIVIA RABELO TEOBALDO,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira
3,3,27525,2025-02-12 15:46:00,5055336 - ALAIDE LIMA DA SILVA,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira
4,4,27526,2025-02-12 16:25:00,2988248 - MONALISA DE PAULO CARLOS,355.0,355.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira
...,...,...,...,...,...,...,...,...,...,...
164,164,29620,2025-06-17 10:38:00,5053182 - MALENA GOMES MARQUES,690.0,690.0,0.0,-,Allyne Fontenele Albuquerque,Terça-feira
165,165,29627,2025-06-17 14:28:00,5066378 - MARIA CLARA DA COSTA MONTEIRO,140.0,140.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira
166,166,29630,2025-06-17 15:15:00,5066388 - FRANCISCO MARCIANO DA SILVA,340.0,340.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira
167,167,29634,2025-06-17 15:40:00,5046467 - EDUARDO FRANCISCO FILHO,175.0,175.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira
168,168,168,NaT,NaN,82450.5,60607.5,21843.0,-,NaN,None

In [54]:
import re

In [55]:
df

,Unnamed: 0,Cód,Orçamento,Cliente,Total,Pago,Devedor,Pagamento fora do período,Dentista,Dia_semana
0,0,27434,2025-02-10 09:53:00,5020538 - FABIA MOTA VASCONCELOS,150.0,150.0,0.0,-,Ana Karine Duarte Maia,Segunda-feira
1,1,27467,2025-02-11 10:00:00,5055076 - RENARA MIRANDA,300.0,300.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira
2,2,27469,2025-02-11 10:36:00,5054903 - ANA LIVIA RABELO TEOBALDO,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira
3,3,27525,2025-02-12 15:46:00,5055336 - ALAIDE LIMA DA SILVA,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira
4,4,27526,2025-02-12 16:25:00,2988248 - MONALISA DE PAULO CARLOS,355.0,355.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira
...,...,...,...,...,...,...,...,...,...,...
164,164,29620,2025-06-17 10:38:00,5053182 - MALENA GOMES MARQUES,690.0,690.0,0.0,-,Allyne Fontenele Albuquerque,Terça-feira
165,165,29627,2025-06-17 14:28:00,5066378 - MARIA CLARA DA COSTA MONTEIRO,140.0,140.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira
166,166,29630,2025-06-17 15:15:00,5066388 - FRANCISCO MARCIANO DA SILVA,340.0,340.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira
167,167,29634,2025-06-17 15:40:00,5046467 - EDUARDO FRANCISCO FILHO,175.0,175.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira
168,168,168,NaT,NaN,82450.5,60607.5,21843.0,-,NaN,None

In [56]:
import re
def extrair_turno(data_srt):
    if pd.isnull(data_srt):
        return "Sem Horário"

    hora = data_srt.hour  # pega a hora direto do datetime

    if 5 <= hora < 12:
        return "Manhã"
    elif 12 <= hora < 18:
        return "Tarde"
    elif 0 <= hora <= 23:
        return "Noite"
    else:
        return "Sem Horário"


    # Define o turno
    if 5 <= hora < 12:
        return "Manhã"
    elif 12 <= hora < 18:
        return "Tarde"
    elif 0 <= hora <= 23:
        return "Noite"
    else:
        return "Sem Horário"

df["Turno"]=df["Orçamento"].apply(extrair_turno)
df

,Unnamed: 0,Cód,Orçamento,Cliente,Total,Pago,Devedor,Pagamento fora do período,Dentista,Dia_semana,Turno
0,0,27434,2025-02-10 09:53:00,5020538 - FABIA MOTA VASCONCELOS,150.0,150.0,0.0,-,Ana Karine Duarte Maia,Segunda-feira,Manhã
1,1,27467,2025-02-11 10:00:00,5055076 - RENARA MIRANDA,300.0,300.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira,Manhã
2,2,27469,2025-02-11 10:36:00,5054903 - ANA LIVIA RABELO TEOBALDO,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira,Manhã
3,3,27525,2025-02-12 15:46:00,5055336 - ALAIDE LIMA DA SILVA,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira,Tarde
4,4,27526,2025-02-12 16:25:00,2988248 - MONALISA DE PAULO CARLOS,355.0,355.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira,Tarde
...,...,...,...,...,...,...,...,...,...,...,...
164,164,29620,2025-06-17 10:38:00,5053182 - MALENA GOMES MARQUES,690.0,690.0,0.0,-,Allyne Fontenele Albuquerque,Terça-feira,Manhã
165,165,29627,2025-06-17 14:28:00,5066378 - MARIA CLARA DA COSTA MONTEIRO,140.0,140.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde
166,166,29630,2025-06-17 15:15:00,5066388 - FRANCISCO MARCIANO DA SILVA,340.0,340.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde
167,167,29634,2025-06-17 15:40:00,5046467 - EDUARDO FRANCISCO FILHO,175.0,175.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde
168,168,168,NaT,NaN,82450.5,60607.5,21843.0,-,NaN,None,Sem Horário

In [57]:
df["Dentista"].value_counts()

Dentista
Joana Glaucia Felipe De Almeida    42
Ana Karine Duarte Maia             40
Allyne Fontenele Albuquerque       35
Ana Larissa Amaral De Medeiros     17
Italo Rodrigues Castelo Branco     10
Julio Lima Lucas                    8
Luciane Alves Nunes                 6
Flavia Cristina Dantas Freitas      4
Aline Fernandes De Oliveira         4
Erica De Paula Cardoso              1
Gilson Soares De Assis              1
Name: count, dtype: int64

In [58]:
def calcular_valor_vendido(row):
    if row['Total'] == row['Pago'] and row['Devedor'] == 0:
        return row['Total']
    elif row['Devedor'] != 0:
        return row['Pago']
    else:
        return 0

In [59]:
df["valor vendido dentista"]=df.apply(calcular_valor_vendido,axis=1)
df

,Unnamed: 0,Cód,Orçamento,Cliente,Total,Pago,Devedor,Pagamento fora do período,Dentista,Dia_semana,Turno,valor vendido dentista
0,0,27434,2025-02-10 09:53:00,5020538 - FABIA MOTA VASCONCELOS,150.0,150.0,0.0,-,Ana Karine Duarte Maia,Segunda-feira,Manhã,150.0
1,1,27467,2025-02-11 10:00:00,5055076 - RENARA MIRANDA,300.0,300.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira,Manhã,300.0
2,2,27469,2025-02-11 10:36:00,5054903 - ANA LIVIA RABELO TEOBALDO,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira,Manhã,180.0
3,3,27525,2025-02-12 15:46:00,5055336 - ALAIDE LIMA DA SILVA,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira,Tarde,180.0
4,4,27526,2025-02-12 16:25:00,2988248 - MONALISA DE PAULO CARLOS,355.0,355.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira,Tarde,355.0
...,...,...,...,...,...,...,...,...,...,...,...,...
164,164,29620,2025-06-17 10:38:00,5053182 - MALENA GOMES MARQUES,690.0,690.0,0.0,-,Allyne Fontenele Albuquerque,Terça-feira,Manhã,690.0
165,165,29627,2025-06-17 14:28:00,5066378 - MARIA CLARA DA COSTA MONTEIRO,140.0,140.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde,140.0
166,166,29630,2025-06-17 15:15:00,5066388 - FRANCISCO MARCIANO DA SILVA,340.0,340.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde,340.0
167,167,29634,2025-06-17 15:40:00,5046467 - EDUARDO FRANCISCO FILHO,175.0,175.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde,175.0
168,168,168,NaT,NaN,82450.5,60607.5,21843.0,-,NaN,None,Sem Horário,60607.5

In [60]:
df["Orçamento"] = pd.to_datetime(df["Orçamento"], format="%d/%m/%Y %H:%M", errors="coerce")
def dia_da_semana(data):
    dias = {
        0: "Segunda-feira",
        1: "Terça-feira",
        2: "Quarta-feira",
        3: "Quinta-feira",
        4: "Sexta-feira",
        5: "Sábado",
        6: "Domingo"
    }
    if pd.notnull(data):
        return dias[data.weekday()]
    return None

In [61]:
df

,Unnamed: 0,Cód,Orçamento,Cliente,Total,Pago,Devedor,Pagamento fora do período,Dentista,Dia_semana,Turno,valor vendido dentista
0,0,27434,2025-02-10 09:53:00,5020538 - FABIA MOTA VASCONCELOS,150.0,150.0,0.0,-,Ana Karine Duarte Maia,Segunda-feira,Manhã,150.0
1,1,27467,2025-02-11 10:00:00,5055076 - RENARA MIRANDA,300.0,300.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira,Manhã,300.0
2,2,27469,2025-02-11 10:36:00,5054903 - ANA LIVIA RABELO TEOBALDO,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Terça-feira,Manhã,180.0
3,3,27525,2025-02-12 15:46:00,5055336 - ALAIDE LIMA DA SILVA,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira,Tarde,180.0
4,4,27526,2025-02-12 16:25:00,2988248 - MONALISA DE PAULO CARLOS,355.0,355.0,0.0,-,Ana Larissa Amaral De Medeiros,Quarta-feira,Tarde,355.0
...,...,...,...,...,...,...,...,...,...,...,...,...
164,164,29620,2025-06-17 10:38:00,5053182 - MALENA GOMES MARQUES,690.0,690.0,0.0,-,Allyne Fontenele Albuquerque,Terça-feira,Manhã,690.0
165,165,29627,2025-06-17 14:28:00,5066378 - MARIA CLARA DA COSTA MONTEIRO,140.0,140.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde,140.0
166,166,29630,2025-06-17 15:15:00,5066388 - FRANCISCO MARCIANO DA SILVA,340.0,340.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde,340.0
167,167,29634,2025-06-17 15:40:00,5046467 - EDUARDO FRANCISCO FILHO,175.0,175.0,0.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde,175.0
168,168,168,NaT,NaN,82450.5,60607.5,21843.0,-,NaN,None,Sem Horário,60607.5

In [62]:
indices_diferentes_0=df[df["Devedor"]!=0].index
indices_diferentes_0

Index([ 17,  18,  22,  26,  32,  34,  35,  36,  38,  39,  49,  53,  59,  60,
        72,  73,  93,  94, 102, 109, 110, 112, 116, 117, 124, 130, 131, 150,
       159, 168],
      dtype='int64')

In [63]:
nao_fechamentos=df.loc[indices_diferentes_0]
nao_fechamentos

,Unnamed: 0,Cód,Orçamento,Cliente,Total,Pago,Devedor,Pagamento fora do período,Dentista,Dia_semana,Turno,valor vendido dentista
17,17,27668,2025-02-18 14:18:00,5049233 - ANA CLAUDIA BENTO SOARES,380.0,0.0,380.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde,0.0
18,18,27672,2025-02-18 15:11:00,5052088 - JOSE LUCIANO HOLANDA DA SILVA FILHO,420.0,0.0,420.0,-,Julio Lima Lucas,Terça-feira,Tarde,0.0
22,22,27779,2025-02-24 08:39:00,4666236 - FRANCISCA TAINA MARTINS BARROS,90.0,0.0,90.0,-,Allyne Fontenele Albuquerque,Segunda-feira,Manhã,0.0
26,26,27790,2025-02-24 14:56:00,5048389 - VENISSIO DE SOUSA MOURA,1565.0,0.0,1565.0,-,Allyne Fontenele Albuquerque,Segunda-feira,Tarde,0.0
32,32,27950,2025-03-15 09:19:00,5011681 - EDILEUDA MACARIO CAETANO,325.0,0.0,325.0,-,Ana Karine Duarte Maia,Sábado,Manhã,0.0
34,34,27969,2025-03-17 11:44:00,5024863 - DAIANA DE SOUSA SILVA,150.0,0.0,150.0,-,Ana Karine Duarte Maia,Segunda-feira,Manhã,0.0
35,35,27970,2025-03-17 11:46:00,5024863 - DAIANA DE SOUSA SILVA,80.0,0.0,80.0,-,Ana Karine Duarte Maia,Segunda-feira,Manhã,0.0
36,36,27971,2025-03-17 11:47:00,5024863 - DAIANA DE SOUSA SILVA,150.0,0.0,150.0,-,Ana Karine Duarte Maia,Segunda-feira,Manhã,0.0
38,38,28008,2025-03-18 15:21:00,5057497 - AMANDA ALVES DE CASTRO BARBOSA,748.0,0.0,748.0,-,Julio Lima Lucas,Terça-feira,Tarde,0.0
39,39,28040,2025-03-20 15:39:00,5051011 - JOSEFA VALENTIM DA SILVA,1380.0,0.0,1380.0,-,Allyne Fontenele Albuquerque,Quinta-feira,Tarde,0.0
49,49,28110,2025-03-24 17:10:00,5009279 - BRUNA RAIZA XAVIER MORAIS,150.0,0.0,150.0,-,Ana Karine Duarte Maia,Segunda-feira,Tarde,0.0
53,53,28150,2025-03-27 18:04:00,5058214 - SOLANGE SILVA MONTEIRO HOLANDA,355.0,0.0,355.0,-,Ana Larissa Amaral De Medeiros,Quinta-feira,Noite,0.0
59,59,28188,2025-03-29 09:53:00,5058366 - RONIERE PARENTE,1120.0,0.0,1120.0,-,Julio Lima Lucas,Sábado,Manhã,0.0
60,60,28192,2025-03-29 11:46:00,5055217 - VANDERLANDIA MIRANDA DA COSTA,190.0,0.0,190.0,-,Joana Glaucia Felipe De Almeida,Sábado,Manhã,0.0
72,72,28330,2025-04-07 09:26:00,5010983 - ANGELA MICHELE DA SILVA LOPES,690.0,0.0,690.0,-,Allyne Fontenele Albuquerque,Segunda-feira,Manhã,0.0
73,73,28333,2025-04-07 11:48:00,5038643 - JOHN ERICK ALENCAR DA SILVA MATIAS,690.0,0.0,690.0,-,Allyne Fontenele Albuquerque,Segunda-feira,Manhã,0.0
93,93,28706,2025-04-28 11:30:00,5061159 - FRANCISCA LEDA VLADIANA,690.0,0.0,690.0,-,Allyne Fontenele Albuquerque,Segunda-feira,Manhã,0.0
94,94,28758,2025-04-30 15:37:00,5056107 - CARLOS MIGUEL DAVID ABREU,300.0,0.0,300.0,-,Luciane Alves Nunes,Quarta-feira,Tarde,0.0
102,102,28813,2025-05-05 10:05:00,5024294 - SIMONE MENDES DE OLIVEIRA COSTA,350.0,0.0,350.0,-,Allyne Fontenele Albuquerque,Segunda-feira,Manhã,0.0
109,109,28917,2025-05-09 09:44:00,5022135 - FRANCISCO CARLOS DE OLIVEIRA,2920.0,0.0,2920.0,-,Italo Rodrigues Castelo Branco,Sexta-feira,Manhã,0.0
110,110,28919,2025-05-09 09:56:00,5003857 - ROSINE PEREIRA DE SOUZA,1725.0,0.0,1725.0,-,Italo Rodrigues Castelo Branco,Sexta-feira,Manhã,0.0
112,112,28923,2025-05-09 11:02:00,5019728 - MARIA DO SOCORRO BEZERRA,3825.0,0.0,3825.0,-,Italo Rodrigues Castelo Branco,Sexta-feira,Manhã,0.0
116,116,28976,2025-05-12 17:38:00,5061869 - MARIA WANDERLICE LIMA DE OLIVEIRA,1200.0,0.0,1200.0,-,Ana Karine Duarte Maia,Segunda-feira,Tarde,0.0
117,117,29002,2025-05-14 08:16:00,5056110 - FRANCISCO EUGENIO RIBEIRO DO NASCIMENTO,460.0,0.0,460.0,-,Joana Glaucia Felipe De Almeida,Quarta-feira,Manhã,0.0
124,124,29053,2025-05-15 16:55:00,5060760 - MARIA CLARA NUNES DE ALMEIDA,720.0,0.0,720.0,-,Allyne Fontenele Albuquerque,Quinta-feira,Tarde,0.0
130,130,29081,2025-05-16 17:28:00,5054222 - FRANCISCO ERCOS FERREIRA DE MORAES,190.0,0.0,190.0,-,Joana Glaucia Felipe De Almeida,Sexta-feira,Tarde,0.0
131,131,29124,2025-05-20 15:08:00,5051169 - MOISES WASHINGTON M DE LIMA,730.0,0.0,730.0,-,Joana Glaucia Felipe De Almeida,Terça-feira,Tarde,0.0
150,150,29440,2025-06-07 09:15:00,5065684 - RAQUEL FREIRE BARBOSA,150.0,0.0,150.0,-,Ana Karine Duarte Maia,Sábado,Manhã,0.0
159,159,29553,2025-06-13 12:26:00,5066125 - DANIELA ANUNCIADA DOS SANTOS,100.0,0.0,100.0,-,Flavia Cristina Dantas Freitas,Sexta-feira,Tarde,0.0
168,168,168,NaT,NaN,82450.5,60607.5,21843.0,-,NaN,None,Sem Horário,60607.5

In [64]:
fechamentos=df.drop(index=nao_fechamentos.index)

In [65]:
fechamentos["Dentista"].value_counts()

Dentista
Joana Glaucia Felipe De Almeida    37
Ana Karine Duarte Maia             33
Allyne Fontenele Albuquerque       27
Ana Larissa Amaral De Medeiros     16
Italo Rodrigues Castelo Branco      7
Julio Lima Lucas                    5
Luciane Alves Nunes                 5
Aline Fernandes De Oliveira         4
Flavia Cristina Dantas Freitas      3
Erica De Paula Cardoso              1
Gilson Soares De Assis              1
Name: count, dtype: int64

In [66]:
nao_fechamentos["Dentista"].value_counts()

Dentista
Allyne Fontenele Albuquerque       8
Ana Karine Duarte Maia             7
Joana Glaucia Felipe De Almeida    5
Julio Lima Lucas                   3
Italo Rodrigues Castelo Branco     3
Ana Larissa Amaral De Medeiros     1
Luciane Alves Nunes                1
Flavia Cristina Dantas Freitas     1
Name: count, dtype: int64

In [36]:
df

,Unnamed: 0,Cód,Orçamento,Cliente,Total,Pago,Devedor,Pagamento fora do período,Dentista,valor vendido dentista
0,0,27434,2025-02-10 09:53:00,5020538 - FABIA MOTA VASCONCELOS,150.0,150.0,0.0,-,Ana Karine Duarte Maia,150.0
1,1,27467,2025-02-11 10:00:00,5055076 - RENARA MIRANDA,300.0,300.0,0.0,-,Ana Larissa Amaral De Medeiros,300.0
2,2,27469,2025-02-11 10:36:00,5054903 - ANA LIVIA RABELO TEOBALDO,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,180.0
3,3,27525,2025-02-12 15:46:00,5055336 - ALAIDE LIMA DA SILVA,180.0,180.0,0.0,-,Ana Larissa Amaral De Medeiros,180.0
4,4,27526,2025-02-12 16:25:00,2988248 - MONALISA DE PAULO CARLOS,355.0,355.0,0.0,-,Ana Larissa Amaral De Medeiros,355.0
...,...,...,...,...,...,...,...,...,...,...
164,164,29620,2025-06-17 10:38:00,5053182 - MALENA GOMES MARQUES,690.0,690.0,0.0,-,Allyne Fontenele Albuquerque,690.0
165,165,29627,2025-06-17 14:28:00,5066378 - MARIA CLARA DA COSTA MONTEIRO,140.0,140.0,0.0,-,Joana Glaucia Felipe De Almeida,140.0
166,166,29630,2025-06-17 15:15:00,5066388 - FRANCISCO MARCIANO DA SILVA,340.0,340.0,0.0,-,Joana Glaucia Felipe De Almeida,340.0
167,167,29634,2025-06-17 15:40:00,5046467 - EDUARDO FRANCISCO FILHO,175.0,175.0,0.0,-,Joana Glaucia Felipe De Almeida,175.0
168,168,168,NaT,NaN,82450.5,60607.5,21843.0,-,NaN,60607.5