<a href="https://colab.research.google.com/github/Lyanan85/In-GameSeries/blob/venv/Realizando_operacoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploração inicial: Ver as colunas do dataset

In [1]:
import pandas as pd

# Carregar o dataset
df = pd.read_csv('superstore.csv', encoding='ISO-8859-1')

# Exibir as primeiras linhas do dataset para inspecionar
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'superstore.csv'

In [ ]:
# Exibir as colunas do dataset
df.columns

Index(['Linha ID', 'Ordem ID', 'Data Ordem', 'Data Envio', 'Modo Envio',
       'Cliente ID', 'Nome Cliente', 'Segmento', 'PaÃ­s', 'Cidade', 'Estado',
       'Codigo Postal', 'Regiao', 'Produto ID', 'Categoria', 'Sub-Categoria',
       'Nome Produto', 'Vendas', 'Quantidade', 'Desconto', 'Lucro'],
      dtype='object')

# Estatísticas descritivas

In [ ]:
df.describe()

,Linha ID,Codigo Postal,Vendas,Quantidade,Desconto,Lucro
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

> Dica do Allan: O método `describe` é usado para gerar estatísticas descritivas de um DataFrame ou de uma Série. Ele fornece um resumo estatístico útil das colunas numéricas ou categóricas, dependendo do contexto.

#### O que ele retorna para colunas **numéricas**:
- **count**: Quantidade de valores não nulos.
- **mean**: Média dos valores.
- **std**: Desvio padrão.
- **min**: Valor mínimo.
- **25%**: Primeiro quartil (25% dos dados abaixo deste valor).
- **50%**: Mediana (50% dos dados abaixo deste valor).
- **75%**: Terceiro quartil (75% dos dados abaixo deste valor).
- **max**: Valor máximo.



O método `describe` é excelente para obter uma visão geral rápida de seus dados e identificar tendências ou possíveis problemas (como valores ausentes ou outliers).

# Operações nos DataFrames

In [ ]:
# Dividir o DataFrame em dois subconjuntos por região
df_west = df[df['Regiao'] == 'West']
df_south = df[df['Regiao'] == 'South']

In [ ]:
# Somar as vendas ('Vendas') por região
sales_west = df_west['Vendas'].sum()
sales_south = df_south['Vendas'].sum()

In [ ]:
sales_west

725457.8245

In [ ]:
sales_south

391721.905

# Operações condicionais para criar colunas derivadas

In [ ]:
# Criar uma coluna indicando se houve desconto
df['Desconto_Aplicado'] = df['Desconto'] > 0

# Exibir as primeiras linhas com a nova coluna
print("\nNova coluna 'Desconto_aplicado':")
df[['Desconto', 'Desconto_Aplicado']].head()

Nova coluna 'Desconto_aplicado':

   Desconto  Desconto_Aplicado
0      0.00              False
1      0.00              False
2      0.00              False
3      0.45               True
4      0.20               True

# Criação de novas colunas

In [ ]:
# Criar uma nova coluna de "Lucro por Unidade" (Lucro / Quantidade)
df['Lucro por Unidade'] = df['Lucro'] / df['Quantidade']

In [ ]:
df[['Lucro', 'Quantidade', 'Lucro por Unidade']].head()

      Lucro  Quantidade  Lucro por Unidade
0   41.9136           2            20.9568
1  219.5820           3            73.1940
2    6.8714           2             3.4357
3 -383.0310           5           -76.6062
4    2.5164           2             1.2582

# Funções customizadas com .apply()

> Dica do Allan: O método `apply` do pandas é uma ferramenta poderosa para aplicar funções personalizadas a colunas ou linhas de um DataFrame. Ele é especialmente útil quando você precisa realizar transformações ou cálculos que não estão disponíveis diretamente nos métodos nativos da biblioteca. Por exemplo, você pode usar `apply` para aplicar uma função lambda a cada elemento de uma coluna específica, como calcular a raiz quadrada de valores numéricos ou formatar strings. Para aplicá-lo em colunas, utilize o parâmetro `axis=0` (comportamento padrão), e para linhas, defina `axis=1`. Apesar de sua flexibilidade, é importante usá-lo com cautela em grandes conjuntos de dados, pois pode ser mais lento em comparação com métodos vetorizados do pandas, que são otimizados para desempenho.

In [ ]:
df['Lucro']

0        41.9136
1       219.5820
2         6.8714
3      -383.0310
4         2.5164
          ...
9989      4.1028
9990     15.6332
9991     19.3932
9992     13.3200
9993     72.9480
Name: Lucro, Length: 9994, dtype: float64

In [ ]:
# Criar uma função para categorizar o lucro
def categoriza_lucro(lucro):
    if lucro > 50:
        return 'Alta margem'
    elif lucro > 0:
        return 'Margem positiva'
    else:
        return 'Prejuízo'

# Aplicar a função
df['Categoria_Lucro'] = df['Lucro'].apply(categoriza_lucro)

# Exibir as primeiras linhas com a nova coluna
df[['Lucro', 'Categoria_Lucro']].head()

      Lucro  Categoria_Lucro
0   41.9136  Margem positiva
1  219.5820      Alta margem
2    6.8714  Margem positiva
3 -383.0310         Prejuízo
4    2.5164  Margem positiva

# Função lambda

In [ ]:
#Calculando a margem de lucro como porcentagem.
df['Margem Lucro (%)'] = df.apply(lambda x: (x['Lucro'] / x['Vendas']) * 100, axis=1)
df['Margem Lucro (%)']

0       16.00
1       30.00
2       47.00
3      -40.00
4       11.25
        ...
9989    16.25
9990    17.00
9991     7.50
9992    45.00
9993    30.00
Name: Margem Lucro (%), Length: 9994, dtype: float64

In [ ]:
df['Nivel Vendas'] = df['Vendas'].apply(lambda x: 'Alta' if x > 500 else 'Baixa')
df['Nivel Vendas']

0       Baixa
1        Alta
2       Baixa
3        Alta
4       Baixa
        ...
9989    Baixa
9990    Baixa
9991    Baixa
9992    Baixa
9993    Baixa
Name: Nivel Vendas, Length: 9994, dtype: object

In [ ]:
df['Desconto Elevado'] = df['Desconto'].apply(lambda x: True if x > 0.2 else False)
df['Desconto Elevado']

0       False
1       False
2       False
3        True
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Name: Desconto Elevado, Length: 9994, dtype: bool

In [2]:
import pandas as pd

# Dados das plantas
dados = {
    'Especie': ['Mangifera indica', 'Eucalyptus globulus', 'Pinus elliottii', 'Anacardium occidentale',
                'Coffea arabica', 'Hevea brasiliensis', 'Carica papaya', 'Theobroma cacao',
                'Cocos nucifera', 'Bertholletia excelsa'],
    'Regiao': ['Norte', 'Sul', 'Leste', 'Norte', 'Sul', 'Oeste', 'Leste', 'Norte', 'Oeste', 'Norte'],
    'AlturaMedia': [15, 30, 25, 12, 3, 20, 5, 10, 18, 40]
}

# Criando o DataFrame
df_plantas = pd.DataFrame(dados)

In [3]:
df_plantas

                  Especie Regiao  AlturaMedia
0        Mangifera indica  Norte           15
1     Eucalyptus globulus    Sul           30
2         Pinus elliottii  Leste           25
3  Anacardium occidentale  Norte           12
4          Coffea arabica    Sul            3
5      Hevea brasiliensis  Oeste           20
6           Carica papaya  Leste            5
7         Theobroma cacao  Norte           10
8          Cocos nucifera  Oeste           18
9    Bertholletia excelsa  Norte           40

In [9]:
plantas_baixas=df_plantas[df_plantas["AlturaMedia"]<=15]
plantas_altas=df_plantas[df_plantas["AlturaMedia"]>15]
display(plantas_baixas)
print("-"*50)
display(plantas_altas)

                  Especie Regiao  AlturaMedia
0        Mangifera indica  Norte           15
3  Anacardium occidentale  Norte           12
4          Coffea arabica    Sul            3
6           Carica papaya  Leste            5
7         Theobroma cacao  Norte           10

--------------------------------------------------

                Especie Regiao  AlturaMedia
1   Eucalyptus globulus    Sul           30
2       Pinus elliottii  Leste           25
5    Hevea brasiliensis  Oeste           20
8        Cocos nucifera  Oeste           18
9  Bertholletia excelsa  Norte           40

In [14]:
soma_baixa=plantas_baixas["AlturaMedia"].sum()
soma_alta=plantas_altas["AlturaMedia"].sum()
print(soma_baixa)
print(soma_alta)

45
133

In [20]:
df_plantas["GrandePorte"]=df_plantas["AlturaMedia"]>=20
display(df_plantas)
print("-"*50)
print(df_plantas[["Especie","AlturaMedia","GrandePorte"]])

                  Especie Regiao  AlturaMedia  GrandePorte
0        Mangifera indica  Norte           15        False
1     Eucalyptus globulus    Sul           30         True
2         Pinus elliottii  Leste           25         True
3  Anacardium occidentale  Norte           12        False
4          Coffea arabica    Sul            3        False
5      Hevea brasiliensis  Oeste           20         True
6           Carica papaya  Leste            5        False
7         Theobroma cacao  Norte           10        False
8          Cocos nucifera  Oeste           18        False
9    Bertholletia excelsa  Norte           40         True

--------------------------------------------------
                  Especie  AlturaMedia  GrandePorte
0        Mangifera indica           15        False
1     Eucalyptus globulus           30         True
2         Pinus elliottii           25         True
3  Anacardium occidentale           12        False
4          Coffea arabica            3        False
5      Hevea brasiliensis           20         True
6           Carica papaya            5        False
7         Theobroma cacao           10        False
8          Cocos nucifera           18        False
9    Bertholletia excelsa           40         True

In [26]:
df_plantas["IndicieAlturaRelativa"]=df_plantas["AlturaMedia"]/df_plantas["AlturaMedia"].max()
display(df_plantas)
print("-"*50)
print(df_plantas[["Especie","AlturaMedia","IndicieAlturaRelativa"]])

,Especie,Regiao,AlturaMedia,GrandePorte,IndicieAlturaRelativa
0,Mangifera indica,Norte,15,False,0.375
1,Eucalyptus globulus,Sul,30,True,0.750
2,Pinus elliottii,Leste,25,True,0.625
3,Anacardium occidentale,Norte,12,False,0.300
4,Coffea arabica,Sul,3,False,0.075
5,Hevea brasiliensis,Oeste,20,True,0.500
6,Carica papaya,Leste,5,False,0.125
7,Theobroma cacao,Norte,10,False,0.250
8,Cocos nucifera,Oeste,18,False,0.450
9,Bertholletia excelsa,Norte,40,True,1.000

--------------------------------------------------
                  Especie  AlturaMedia  IndicieAlturaRelativa
0        Mangifera indica           15                  0.375
1     Eucalyptus globulus           30                  0.750
2         Pinus elliottii           25                  0.625
3  Anacardium occidentale           12                  0.300
4          Coffea arabica            3                  0.075
5      Hevea brasiliensis           20                  0.500
6           Carica papaya            5                  0.125
7         Theobroma cacao           10                  0.250
8          Cocos nucifera           18                  0.450
9    Bertholletia excelsa           40                  1.000

In [29]:
dados = {
    'PedidoID': [101, 102, 103, 104, 105],
    'Cliente': ['Alice', 'Bruno', 'Carla', 'Daniel', 'Eduarda'],
    'ValorTotal': [150.00, 200.00, 300.00, 120.00, 500.00],
    'QuantidadeItens': [3, 4, 6, 2, 10]
}

# Criando o DataFrame
df_vendas = pd.DataFrame(dados)
df_vendas

   PedidoID  Cliente  ValorTotal  QuantidadeItens
0       101    Alice       150.0                3
1       102    Bruno       200.0                4
2       103    Carla       300.0                6
3       104   Daniel       120.0                2
4       105  Eduarda       500.0               10

In [33]:
df_vendas["Ticket - Médio"]=df_vendas["ValorTotal"]/df_vendas["QuantidadeItens"]
df_vendas
print(df_vendas)

   PedidoID  Cliente  ValorTotal  QuantidadeItens  Ticket - Médio
0       101    Alice       150.0                3            50.0
1       102    Bruno       200.0                4            50.0
2       103    Carla       300.0                6            50.0
3       104   Daniel       120.0                2            60.0
4       105  Eduarda       500.0               10            50.0

In [35]:
dados = {
    'Aluno': ['Alice', 'Bruno', 'Carla', 'Daniel', 'Eduarda', 'Felipe', 'Gabriela', 'Henrique'],
    'NotaFinal': [95, 82, 67, 45, 78, 88, 50, 30]
}

# Criando o DataFrame
df_alunos = pd.DataFrame(dados)
df_alunos

      Aluno  NotaFinal
0     Alice         95
1     Bruno         82
2     Carla         67
3    Daniel         45
4   Eduarda         78
5    Felipe         88
6  Gabriela         50
7  Henrique         30

In [50]:
def categoriza_desempenho(nota):
  if nota>=90:
    return "Excelente"
  elif nota<=89 and nota>=70:
    return "Bom"
  elif nota<=69 and nota>=50:
    return "Regular"
  else:
     return "Insuficiente"

In [51]:
df_alunos["Desempenho"]=df_alunos["NotaFinal"].apply(categoriza_desempenho)
print(df_alunos[["Aluno","NotaFinal","Desempenho"]])

      Aluno  NotaFinal    Desempenho
0     Alice         95     Excelente
1     Bruno         82           Bom
2     Carla         67       Regular
3    Daniel         45  Insuficiente
4   Eduarda         78           Bom
5    Felipe         88           Bom
6  Gabriela         50       Regular
7  Henrique         30  Insuficiente

In [52]:
df_alunos

      Aluno  NotaFinal    Desempenho
0     Alice         95     Excelente
1     Bruno         82           Bom
2     Carla         67       Regular
3    Daniel         45  Insuficiente
4   Eduarda         78           Bom
5    Felipe         88           Bom
6  Gabriela         50       Regular
7  Henrique         30  Insuficiente

In [54]:
import pandas as pd

# Dados financeiros das pessoas
dados = {
    'Pessoa': ['Ana', 'Bruno', 'Carla', 'Daniel', 'Eduarda', 'Felipe', 'Gabriela', 'Henrique'],
    'Ganhos': [5000, 4000, 3500, 6000, 2500, 7000, 3000, 4500],
    'Despesas': [3000, 2500, 2000, 5000, 2000, 6000, 2500, 4000]
}

# Criando o DataFrame
df_financas = pd.DataFrame(dados)
df_financas

     Pessoa  Ganhos  Despesas
0       Ana    5000      3000
1     Bruno    4000      2500
2     Carla    3500      2000
3    Daniel    6000      5000
4   Eduarda    2500      2000
5    Felipe    7000      6000
6  Gabriela    3000      2500
7  Henrique    4500      4000

In [61]:
df_financas["Economia(%)"]=df_financas.apply(
    lambda x:((x["Ganhos"]-x["Despesas"])/x["Ganhos"])*100,axis=1)
df_financas

     Pessoa  Ganhos  Despesas  Economia(%)
0       Ana    5000      3000    40.000000
1     Bruno    4000      2500    37.500000
2     Carla    3500      2000    42.857143
3    Daniel    6000      5000    16.666667
4   Eduarda    2500      2000    20.000000
5    Felipe    7000      6000    14.285714
6  Gabriela    3000      2500    16.666667
7  Henrique    4500      4000    11.111111

In [63]:
dados = {
    'Produto': ['Notebook', 'Mouse', 'Teclado', 'Monitor', 'Cadeira', 'Impressora', 'Pen Drive', 'Mesa'],
    'Estoque': [30, 150, 45, 20, 60, 10, 80, 50]
}

# Criando o DataFrame
df_produtos = pd.DataFrame(dados)
df_produtos

      Produto  Estoque
0    Notebook       30
1       Mouse      150
2     Teclado       45
3     Monitor       20
4     Cadeira       60
5  Impressora       10
6   Pen Drive       80
7        Mesa       50

In [65]:
df_produtos["Estoque Baixo"]=df_produtos.apply(lambda x: True if x["Estoque"]<50 else False,axis=1)
df_produtos

      Produto  Estoque  Estoque Baixo
0    Notebook       30           True
1       Mouse      150          False
2     Teclado       45           True
3     Monitor       20           True
4     Cadeira       60          False
5  Impressora       10           True
6   Pen Drive       80          False
7        Mesa       50          False

In [67]:
dados = {
    'Vendedor': ['Ana', 'Bruno', 'Carla', 'Daniel', 'Eduarda', 'Felipe', 'Gabriela', 'Henrique'],
    'Meta': [20000, 15000, 18000, 25000, 12000, 30000, 10000, 22000],
    'Vendas': [22000, 14000, 19000, 24000, 13000, 28000, 9000, 23000],
    'Comissão (%)': [5, 4, 6, 5, 4, 7, 3, 6]
}

# Criando o DataFrame
df_vendas = pd.DataFrame(dados)
df_vendas

   Vendedor   Meta  Vendas  Comissão (%)
0       Ana  20000   22000             5
1     Bruno  15000   14000             4
2     Carla  18000   19000             6
3    Daniel  25000   24000             5
4   Eduarda  12000   13000             4
5    Felipe  30000   28000             7
6  Gabriela  10000    9000             3
7  Henrique  22000   23000             6

In [72]:
df_vendas["Desempenho"]=df_vendas.apply(lambda x:"Atingiu a Meta" if x["Vendas"]>=x["Meta"] else "Não Atingiu a Meta",axis=1)
df_vendas

   Vendedor   Meta  Vendas  Comissão (%)          Desempenho
0       Ana  20000   22000             5      Atingiu a Meta
1     Bruno  15000   14000             4  Não Atingiu a Meta
2     Carla  18000   19000             6      Atingiu a Meta
3    Daniel  25000   24000             5  Não Atingiu a Meta
4   Eduarda  12000   13000             4      Atingiu a Meta
5    Felipe  30000   28000             7  Não Atingiu a Meta
6  Gabriela  10000    9000             3  Não Atingiu a Meta
7  Henrique  22000   23000             6      Atingiu a Meta

In [78]:
df_vendas["Comissão Recebida"]=df_vendas.apply(lambda x:(x["Comissão (%)"]/100) *x["Vendas"],axis=1)
df_vendas

,Vendedor,Meta,Vendas,Comissão (%),Desempenho,Comissão Recebida
0,Ana,20000,22000,5,Atingiu a Meta,1100.0
1,Bruno,15000,14000,4,Não Atingiu a Meta,560.0
2,Carla,18000,19000,6,Atingiu a Meta,1140.0
3,Daniel,25000,24000,5,Não Atingiu a Meta,1200.0
4,Eduarda,12000,13000,4,Atingiu a Meta,520.0
5,Felipe,30000,28000,7,Não Atingiu a Meta,1960.0
6,Gabriela,10000,9000,3,Não Atingiu a Meta,270.0
7,Henrique,22000,23000,6,Atingiu a Meta,1380.0

In [81]:
dados = {
    'Texto': [
        "Bom dia! ☀️ Começando mais uma semana produtiva!",
        "Novo produto chegando! 🎉 #novidade #lancamento",
        "Promoção relâmpago ⚡ Aproveitem! #promo #desconto",
        "Boa noite pessoal! 🌙 Até amanhã! #boanoite",
        "Dica do dia: 💡 Mantenha-se hidratado! #saude #bemestar"
    ],
    'Horário': ['07:30', '15:45', '12:20', '22:15', '10:00'],
    'Hashtags': ['', 'novidade,lancamento', 'promo,desconto', 'boanoite', 'saude,bemestar'],
    'Caracteres_Emoji': ['☀️', '🎉', '⚡', '🌙', '💡']
}

df_posts = pd.DataFrame(dados)
df_posts

,Texto,Horário,Hashtags,Caracteres_Emoji
0,Bom dia! ☀️ Começando mais uma semana produtiva!,07:30,,☀️
1,Novo produto chegando! 🎉 #novidade #lancamento,15:45,"novidade,lancamento",🎉
2,Promoção relâmpago ⚡ Aproveitem! #promo #desconto,12:20,"promo,desconto",⚡
3,Boa noite pessoal! 🌙 Até amanhã! #boanoite,22:15,boanoite,🌙
4,Dica do dia: 💡 Mantenha-se hidratado! #saude #...,10:00,"saude,bemestar",💡

In [82]:
def get_periodo(horario):
    hora = int(horario.split(':')[0])
    if 0 <= hora < 6:
        return 'Madrugada'
    elif 6 <= hora < 12:
        return 'Manhã'
    elif 12 <= hora < 18:
        return 'Tarde'
    else:
        return 'Noite'

# Função para análise do conteúdo
def analisar_conteudo(row):
    num_hashtags = len([tag for tag in row['Hashtags'].split(',') if tag])
    num_emojis = len(row['Caracteres_Emoji'])
    comprimento_texto = len(row['Texto'])

    return {
        'num_hashtags': num_hashtags,
        'num_emojis': num_emojis,
        'comprimento_texto': comprimento_texto
    }

In [83]:
df_posts["Periodo - dia"]=df_posts["Horário"].apply(get_periodo)
df_posts["Analise_Conteúdo"]=df_posts.apply(analisar_conteudo,axis=1)
df_posts

,Texto,Horário,Hashtags,Caracteres_Emoji,Periodo - dia,Analise_Conteúdo
0,Bom dia! ☀️ Começando mais uma semana produtiva!,07:30,,☀️,Manhã,"{'num_hashtags': 0, 'num_emojis': 2, 'comprime..."
1,Novo produto chegando! 🎉 #novidade #lancamento,15:45,"novidade,lancamento",🎉,Tarde,"{'num_hashtags': 2, 'num_emojis': 1, 'comprime..."
2,Promoção relâmpago ⚡ Aproveitem! #promo #desconto,12:20,"promo,desconto",⚡,Tarde,"{'num_hashtags': 2, 'num_emojis': 1, 'comprime..."
3,Boa noite pessoal! 🌙 Até amanhã! #boanoite,22:15,boanoite,🌙,Noite,"{'num_hashtags': 1, 'num_emojis': 1, 'comprime..."
4,Dica do dia: 💡 Mantenha-se hidratado! #saude #...,10:00,"saude,bemestar",💡,Manhã,"{'num_hashtags': 2, 'num_emojis': 1, 'comprime..."